#!/usr/bin/env bash
# Install img2webp into a local virtual environment (.venv) and put an
# `image-to-webp` command on the system PATH (libwebp already owns `img2webp`).
#
#   ./install.sh               install
#   ./install.sh --uninstall   remove the system command
#   BIN_DIR=~/bin ./install.sh install the command elsewhere
set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(pwd)"
VENV="$ROOT/.venv"
CMD_NAME="${CMD_NAME:-image-to-webp}"

# /usr/bin is read-only on macOS (System Integrity Protection), so use /usr/local/bin there.
if [ -z "${BIN_DIR:-}" ]; then
  if [ "$(uname -s)" = "Darwin" ]; then BIN_DIR="/usr/local/bin"; else BIN_DIR="/usr/bin"; fi
fi
TARGET="$BIN_DIR/$CMD_NAME"

# Run a command, escalating with sudo only if the target dir isn't writable.
as_root() {
  if [ -w "$BIN_DIR" ] || { [ ! -e "$BIN_DIR" ] && [ -w "$(dirname "$BIN_DIR")" ]; }; then
    "$@"
  else
    echo "    (sudo required to write to $BIN_DIR)"
    sudo "$@"
  fi
}

if [ "${1:-}" = "--uninstall" ]; then
  if [ -e "$TARGET" ]; then
    as_root rm -f "$TARGET"
    echo "Removed $TARGET"
  else
    echo "Nothing to remove at $TARGET"
  fi
  exit 0
fi

PYTHON="${PYTHON:-}"
if [ -z "$PYTHON" ]; then
  for c in python3 python; do
    if command -v "$c" >/dev/null 2>&1; then PYTHON="$c"; break; fi
  done
fi
[ -n "$PYTHON" ] || { echo "Error: python3 not found." >&2; exit 1; }

"$PYTHON" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' \
  || { echo "Error: Python >= 3.9 required (found $("$PYTHON" -V 2>&1))." >&2; exit 1; }

echo "==> Creating virtual environment in $VENV"
[ -d "$VENV" ] || "$PYTHON" -m venv "$VENV"

echo "==> Installing dependencies"
"$VENV/bin/python" -m pip install --quiet --upgrade pip
"$VENV/bin/python" -m pip install --quiet Pillow
# Optional plugins: install individually so one failure doesn't block the rest.
while IFS= read -r req; do
  req="${req%%#*}"; [ -z "${req// }" ] && continue
  "$VENV/bin/python" -m pip install --quiet "$req" \
    || echo "    Warning: could not install '$req' (related formats will be unavailable)."
done < requirements.txt

if ! "$VENV/bin/python" -c 'import cairosvg' >/dev/null 2>&1; then
  echo "    Note: SVG support needs the cairo library (macOS: 'brew install cairo', Debian/Ubuntu: 'apt install libcairo2')."
fi

chmod +x "$ROOT/img2webp-run"

echo "==> Installing command to $TARGET"
TMP_WRAPPER="$(mktemp)"
cat > "$TMP_WRAPPER" <<WRAPPER
#!/usr/bin/env bash
# Generated by $ROOT/install.sh
exec "$ROOT/img2webp-run" "\$@"
WRAPPER
chmod 755 "$TMP_WRAPPER"
as_root mkdir -p "$BIN_DIR"
as_root mv -f "$TMP_WRAPPER" "$TARGET"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "    Note: $BIN_DIR is not on your PATH; add it to use '$CMD_NAME' directly." ;;
esac

echo "==> Done. Supported formats:"
"$TARGET" --list-formats
echo
echo "Usage: $CMD_NAME INPUT... [options]   (see $CMD_NAME --help)"
